---
server:
  port: 8081
logging:
  config: classpath:logback.xml
xxl:
  job:
    executor:
      logpath: /data/applogs/xxl-job/jobhandler
      appname: xxl-job-executor-sample
      port: 9999
      logretentiondays: -1
      ip:
      heartbeat: 10 #自定义 客户端表明心跳的频率 默认是30秒
    admin:
      addresses: http://10.39.48.110:7001
    accessToken:
