---
server:
  port: 8081
logging:
  config: classpath:logback.xml
xxl:
  job:
    executor:
      logpath: /data/applogs/xxl-job/jobhandler
      appname: xxl-job-executor-sample
      port: 9999
      logretentiondays: -1
      ip:
    admin:
      addresses: http://192.168.199.115:7001
    accessToken:
